version: "3.7"

services:

    netpalm-controller:
        build:
            context: .
            dockerfile: ./netpalm_controller_dockerfile
        environment:
            - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
            - NETPALM_CONFIG=/code/config.json
            - NETPALM_LOG_CONFIG_FILENAME=/code/log-config.yml
        ports:
            - "9001:9000"
        networks:
            - "netpalm-network"
        volumes:
            - ./backend/plugins/extensibles:/code/backend/plugins/extensibles
        depends_on:
            - redis

    netpalm-worker-pinned:
        build:
            context: .
            dockerfile: ./netpalm_pinned_worker_dockerfile
        environment:
          - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
          - NETPALM_CONFIG=/code/config.json
          - NETPALM_LOG_CONFIG_FILENAME=/code/log-config.yml
        depends_on:
<<<<<<< Updated upstream
          - redis
=======
            - netpalm-controller
        volumes:
            - ./backend/plugins/extensibles:/code/backend/plugins/extensibles
>>>>>>> Stashed changes
        networks:
        - "netpalm-network"

    netpalm-worker-fifo:
        build:
            context: .
            dockerfile: ./netpalm_fifo_worker_dockerfile
        environment:
          - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
          - NETPALM_CONFIG=/code/config.json
          - NETPALM_LOG_CONFIG_FILENAME=/code/log-config.yml
        depends_on:
<<<<<<< Updated upstream
          - redis
=======
            - netpalm-controller
        volumes:
            - ./backend/plugins/extensibles:/code/backend/plugins/extensibles
>>>>>>> Stashed changes
        networks:
        - "netpalm-network"

    redis:
        image: redis
        command: redis-server --requirepass Red1zp4ww0rd_

        networks:
        - "netpalm-network"

networks:

  netpalm-network:
    name: "netpalm-network"
